# Generated by Django 2.2.1 on 2019-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190702_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
