# Generated by Django 2.2.1 on 2019-07-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190717_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('file_url', models.FileField(blank=True, upload_to='local_comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, default='image/jpeg', max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_admin', to='users.Admin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post', to='users.Evento')),
            ],
        ),
    ]
