# Generated by Django 2.2.1 on 2019-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
