# Generated by Django 2.2.1 on 2019-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interes',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
