# Generated by Django 2.2.1 on 2019-06-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190609_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
