# Generated by Django 2.2.1 on 2019-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190703_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'email')},
        ),
    ]
